### ISSUE TITLE
interval, exponential, jitter ignored when onAttemptFail() is provided

### ISSUE THREAD

**Issue by radford-for-smpte** [VoodooTeam/async-await-retry#18]
Pretty sure that `interval`, `exponential`, `jitter` are ignored when you provided an `onAttemptFail()`.

**Comment by wallet77** [comment]
Hi @radford-for-smpte 

Indeed but this is an expected behavior, if you provide an `onAttemptFail()` function then you are responsible of the logic when there is an error.
All the values are sent to the function (retry, jitter, etc).
