### ISSUE TITLE
if onAttemptFail is specified, interval is ignored

### ISSUE THREAD

**Issue by timrobinson33** [VoodooTeam/async-await-retry#23]
Hello,

I've noticed that if you use an onAttemptFail handler, the interval parameter is ignored and assumed to be 0. Here's a complete example

```
const startTime = new Date().valueOf()

const theAsyncFunc = async (arg1, arg2) => {
  console.log(new Date().valueOf() - startTime, "async", arg1, arg2)
  throw new Error("barf")
}

return await retry(
  theAsyncFunc,
  ["arg1", "arg2"],
  {
    retriesMax: 5,
    interval:100,
    onAttemptFail: data => {
      console.log("attempt failed", data)
      return true;
    }
  }
)
```

each time it's called, `theAsyncFunc` logs how many milliseconds have elapsed since the start of the test. without the `onAttemptFail` parameter, it logs at 0, 100, 300, 700 and 1500 as you would expect. with the `onAttemptFail` parameter, it logs all the output immediately

**Comment by fkranenburg** [comment]
Got the same issue here, specifying `onAttemptFail` requires me to timeout the code ourself (internally `onAttemptFailFallback` is not fired anymore). Workaround is time returning a promise with timeout inside the onAttempFail parameter.

**Comment by wallet77** [comment]
Hi @timrobinson33 ,

If you use `onAttemptFail`, then you have to manage the retry system by yourself, so interval, exponential backoff, ect, should be managed in your function.

Sorry for the delay!
