### ISSUE TITLE
Add onAttemptFail cb

### ISSUE THREAD

**Issue by atlanteh** [VoodooTeam/async-await-retry#5]
Hi,
Can you please add an onAttemptFail callback?
I think it would be super beneficial as it allows:
* properly logging of the retries
* reject in case of a permanent error
* customizing the delay
 
Also I see that there's already a retryable prop that is not documented :)

**Comment by wallet77** [comment]
Hi @atlanteh,

If I understand you want to call a function just after a rejection ? Or you want it to manage all the error case ?
But it's a good feature anyway !

For the "retryable" property you are right, it was to manage a specific case I encountered in some libraries but we can add some explanations about it.

**Comment by atlanteh** [comment]
I suggest to add an onAttemptFail cb that is async function. If this callback rejects, you stop the retries, and reject with an error (The error from the CB)
Maybe add it to:
https://github.com/VoodooTeam/async-await-retry/blob/5b23495ae185e863d9e83e81ff6df64118b9d65b/src/retry.js#L58-L60

This allows:

- **Properly logging of the retries** - In the error handler we will be able to add some logging to later analyse how many attempts failed and why
- **Reject in case of a permanent error** - If we identify a permanent error that retries won't solve, we can bail out of retry
- Customizing the delay - We can set a regular delay, and in the error handler we might want to add some more delay in case of a service unavailability.

**Comment by vincentvalletvoodoo** [comment]
Hi @atlanteh,

I add the PR for this request : https://github.com/VoodooTeam/async-await-retry/pull/6
