### ISSUE TITLE
Idea: Adding random jitter

### ISSUE THREAD

**Issue by brodin** [VoodooTeam/async-await-retry#7]
It might be good to have random jitter as an option? 

>Suppose you have multiple clients that send messages that collide. They all decide to back off. If they use the same deterministic algorithm to decide how long to wait, they will all retry at the same time -- resulting in another collision. Adding a random factor separates the retries.

https://stackoverflow.com/questions/46939285/why-is-random-jitter-applied-to-back-off-strategies

Good article on jitter https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/

**Comment by wallet77** [comment]
Hi @brodin 

I agree on that point.

**Comment by vincentvalletvoodoo** [comment]
@brodin I created a PR, could you check it?

**Comment by brodin** [comment]
> @brodin I created a PR, could you check it?

It looked great! Sorry for missing your ping and thanks for adding this 🙏

**Comment by vitaly-t** [comment]
Shouldn't something like this be on the outside? [My 2 cents for async retry](https://gist.github.com/vitaly-t/6e3d285854d882b1618c7e435df164c4).
